# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.DateTimeField()),
                ('plate_number', models.CharField(max_length=10)),
                ('road_tax_validation', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('concept', models.CharField(choices=[('ECO', 'Economy'), ('SED', 'Sedan'), ('FAM', 'Family')], help_text='Choose the car the type', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Category'),
        ),
    ]
