# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts', models.DateTimeField(null=True)),
                ('duration', models.DurationField(choices=[(datetime.timedelta(0, 21600), 'Six Hours'), (datetime.timedelta(1), 'One Day'), (datetime.timedelta(7), 'One Week'), (datetime.timedelta(28), 'One Month')], default=datetime.timedelta(1), max_length=2)),
                ('dropoff', models.CharField(max_length=255)),
                ('booking_confirmed', models.BooleanField(default=False)),
                ('car_deliverd', models.BooleanField(default=False)),
                ('car_returned', models.BooleanField(default=False)),
                ('fees_paid', models.BooleanField(default=False)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
