# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 12, 10, 35, 58, 802813, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
